{"uuid":"e5665437-6c40-44da-aba2-2de8ebf3aff2","historyId":"5de67f68fb45dacf4ca080f8b8c6dd17","fullName":"tests.LoginPageTest.testEmailInvalidInput2","labels":[{"name":"package","value":"tests.LoginPageTest"},{"name":"testClass","value":"tests.LoginPageTest"},{"name":"testMethod","value":"testEmailInvalidInput2"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"Findit-App-Automation"},{"name":"subSuite","value":"tests.LoginPageTest"},{"name":"host","value":"Mds-MacBook-Air.local"},{"name":"thread","value":"15759@Mds-MacBook-Air.local.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"testEmailInvalidInput2","status":"skipped","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Appium HTTP server has started and is listening although we were unable to get an OK response from http://127.0.0.1:4723/wd/hub/status. Make sure both the client and the server use the same base path '/wd/hub/' and check the server log for possible error messages occurrences.\nResponse status code: 404\nResponse payload: {\"status\":9,\"value\":{\"error\":\"unknown command\",\"message\":\"The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource\",\"stacktrace\":\"\"}}\nNode.js executable path: /Users/md.abubakkarsiddik/.nvm/versions/node/v18.20.6/bin/node\nArguments: [/Users/md.abubakkarsiddik/.nvm/versions/node/v18.20.6/lib/node_modules/appium/build/lib/main.js, --port, 4723, --address, 0.0.0.0, --log, /Users/md.abubakkarsiddik/Documents/Findit-App-Automation/appium_server_logs.txt, --base-path, /wd/hub/, --relaxed-security]","trace":"io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: Appium HTTP server has started and is listening although we were unable to get an OK response from http://127.0.0.1:4723/wd/hub/status. Make sure both the client and the server use the same base path '/wd/hub/' and check the server log for possible error messages occurrences.\nResponse status code: 404\nResponse payload: {\"status\":9,\"value\":{\"error\":\"unknown command\",\"message\":\"The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource\",\"stacktrace\":\"\"}}\nNode.js executable path: /Users/md.abubakkarsiddik/.nvm/versions/node/v18.20.6/bin/node\nArguments: [/Users/md.abubakkarsiddik/.nvm/versions/node/v18.20.6/lib/node_modules/appium/build/lib/main.js, --port, 4723, --address, 0.0.0.0, --log, /Users/md.abubakkarsiddik/Documents/Findit-App-Automation/appium_server_logs.txt, --base-path, /wd/hub/, --relaxed-security]\n\tat io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:192)\n\tat pages.BasePage.startAppiumServer(BasePage.java:76)\n\tat pages.BasePage.initializeDriver(BasePage.java:44)\n\tat tests.BaseTest.setup(BaseTest.java:47)\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)\n\tat org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)\n\tat org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)\n\tat org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:833)\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:600)\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1596)\n\tat org.testng.TestRunner.privateRun(TestRunner.java:739)\n\tat org.testng.TestRunner.run(TestRunner.java:614)\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:421)\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:312)\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1208)\n\tat org.testng.TestNG.runSuites(TestNG.java:1112)\n\tat org.testng.TestNG.run(TestNG.java:1079)\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\nCaused by: io.appium.java_client.service.local.AppiumServerAvailabilityChecker$ConnectionError: ConnectionError\n\tat io.appium.java_client.service.local.AppiumServerAvailabilityChecker.checkResponse(AppiumServerAvailabilityChecker.java:91)\n\tat io.appium.java_client.service.local.AppiumServerAvailabilityChecker.waitUntilAvailable(AppiumServerAvailabilityChecker.java:62)\n\tat io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:144)\n\tat io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:185)\n\t... 32 more\n"},"stage":"finished","description":"Verify Email Input validation with 'abc@gmail'","steps":[],"attachments":[],"parameters":[],"start":1744001634253,"stop":1744001634254}